FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:fa2f6b1151ac0336a90785b17436572a9797284b9eb833d14c13de45a4ba1ef2

VOLUME ["/var/lib/mysql", "/var/lib/backup", "/etc/mysql/conf.d", "/etc/mysql/init.d"]
EXPOSE 3306

WORKDIR /var/lib/mysql
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/mysql && \
  groupadd -g 1000 mysql && \
  useradd -u 1000 -d /var/lib/mysql -g mysql -s /bin/bash -m mysql && \
  apk add mariadb mariadb-client mariadb-server-utils tzdata && \
  rm -rf /var/cache/apk/* /etc/mysql/* /etc/my.cnf* /var/lib/mysql/*

COPY ./overlay /
