FROM webhippie/alpine:latest-amd64@sha256:01c7b6c25bb14db76c9a75e6f315d1b8bd03e731365dd66fa2e8face8c701f40

VOLUME ["/var/lib/mysql", "/var/lib/backup", "/etc/mysql/conf.d", "/etc/mysql/init.d"]
EXPOSE 3306

WORKDIR /var/lib/mysql
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/mysql && \
  groupadd -g 1000 mysql && \
  useradd -u 1000 -d /var/lib/mysql -g mysql -s /bin/bash -m mysql && \
  apk add mariadb mariadb-client mariadb-server-utils tzdata && \
  rm -rf /var/cache/apk/* /etc/mysql/* /etc/my.cnf* /var/lib/mysql/*

COPY ./overlay /
