#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname *.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="mysqld_safe"

if [ ! -d "/var/lib/mysql/mysql" ]
then
  if [ -z "${MARIADB_ROOT_PASSWORD}" ]
  then
    echo >&2 "Error: Database is uninitialized and MARIADB_ROOT_PASSWORD not set"
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi

  echo "> running mysql_install_db..."
  mysql_install_db --user=mysql --datadir="/var/lib/mysql"
  echo "> finished mysql_install_db"

  INIT_FILE="/tmp/mariadb-boot.sql"

  echo "" >| ${INIT_FILE}
  echo "DELETE FROM mysql.user;" >> ${INIT_FILE}
  echo "CREATE USER 'root'@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';" >> ${INIT_FILE}
  echo "GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;" >> ${INIT_FILE}
  echo "DROP DATABASE IF EXISTS test;" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}

  if [[ -n "${MARIADB_USERNAME}" && -n "${MARIADB_DATABASE}" ]]
  then
    DATABASES=$(echo ${MARIADB_DATABASE} | tr "," "\n")

    for DATABASE in ${DATABASES}
    do
      echo "CREATE DATABASE IF NOT EXISTS \`${DATABASE}\`;" >> ${INIT_FILE}
      echo "GRANT ALL PRIVILEGES ON \`${DATABASE}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
    done

    echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
  fi

  if [[ -n "${MARIADB_USERNAME}" && -z "${MARIADB_DATABASE}" ]]
  then
    echo "CREATE DATABASE IF NOT EXISTS \`${MARIADB_USERNAME}\`;" >> ${INIT_FILE}
    echo "GRANT ALL PRIVILEGES ON \`${MARIADB_USERNAME}\`.* TO '${MARIADB_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE}
    echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
  fi

  STARTCMD="${STARTCMD} --init-file=${INIT_FILE}"
fi

echo "> starting mariadb service"
exec ${STARTCMD}
