#!/bin/bash
source /usr/bin/entrypoint

echo "> writing mariadb config"
/usr/bin/gomplate -V \
  -o /etc/mysql/my.cnf \
  -f /etc/templates/my.cnf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

if [[ "${MARIADB_SKIP_CHOWN}" != "true" ]]
then
  echo "> chown data directory"
  find /var/lib/mysql \( \! -user mysql -o \! -group mysql \) -print0 | xargs -0 -r chown mysql:mysql
fi
