#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

STARTCMD="/usr/bin/mysqld_safe"

if [ ! -d "/var/lib/mysql/mysql" ]
then
  if [ -z "${MARIADB_ROOT_PASSWORD}" ]
  then
    echo >&2 "Error: Database is uninitialized and MARIADB_ROOT_PASSWORD not set"
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi

  echo "Running mysql_install_db..."
  mysql_install_db --user=mysql --datadir="/var/lib/mysql"
  echo "Finished mysql_install_db"

  INIT_FILE="/tmp/mariadb-boot.sql"

  echo "" >| ${INIT_FILE}
  echo "DELETE FROM mysql.user;" >> ${INIT_FILE}
  echo "CREATE USER 'root'@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';" >> ${INIT_FILE}
  echo "GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;" >> ${INIT_FILE}
  echo "DROP DATABASE IF EXISTS test;" >> ${INIT_FILE}
  echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}

  NEW_DB__NAME=${MARIADB_DATABASE:-$MARIADB_USERNAME}
  if [ ! -z "${NEW_DB__NAME}" ]
  then
    echo "CREATE DATABASE IF NOT EXISTS \`${NEW_DB__NAME}\`;" >> ${INIT_FILE}

    NEW_DB__USER=${MARIADB_USERNAME:-root}
    if [ "$NEW_DB__USER" != "root" ]
    then
      echo "CREATE USER IF NOT EXISTS '${NEW_DB__USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';" >> ${INIT_FILE} # is able to create an User with NO Password
      echo "GRANT ALL PRIVILEGES ON \`${NEW_DB__NAME}\`.* TO '${NEW_DB__USER}'@'%';" >> ${INIT_FILE}
      echo "FLUSH PRIVILEGES;" >> ${INIT_FILE}
    fi
  fi

  STARTCMD="${STARTCMD} --init-file=${INIT_FILE}"
fi

exec ${STARTCMD}
