#!/usr/bin/env bash
# Usage: manage remove <username>
# Summary: Create a database
# Help: This command is used to create a database
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

USERNAME=$1

if [ -z "${USERNAME}" ]
then
  echo "Please provide a username"
  exit 1
fi

read -r -d "" QUERY <<-EOSQL
DROP USER IF EXISTS '${USERNAME}'@'%';
DROP DATABASE IF EXISTS \`${USERNAME}\`;
FLUSH PRIVILEGES;
EOSQL

echo "${QUERY}" | mysql -uroot -p${MARIADB_ROOT_PASSWORD}
