#!/usr/bin/env bash
# Usage: manage show
# Summary: Show databases
# Help: This command is used to list databases
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

QUERY=$(cat <<EOSQL
SHOW DATABASE;
EOSQL
)

echo "${QUERY}" | mysql -uroot -p${MARIADB_ROOT_PASSWORD}
